[tools]
lazygit = "latest"
ripgrep = "latest"
bat = "latest"
fd = "latest"
neovim = "latest"
eza = "latest"
zellij = "latest"
usage = "latest"
glow = "1.5.0"
go = "latest"
node = "22.9.0"
ruby = "3.3.10"
rust = "stable"
java = "temurin-25.0.2+10.0.LTS"
gum = "latest"
crush = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
