[plugins]
lazydocker = "https://github.com/comdotlinux/asdf-lazydocker.git"

[tools]
lazydocker = "0.23.3"
lazygit = "latest"
ripgrep = "latest"
bat = "latest"
fd = "latest"
neovim = "latest"
git = "latest"
glow = "latest"
eza = "0.18.17"
zellij = "0.40.1"
usage = "latest"
