[tools]
lazygit = "latest"
ripgrep = "latest"
bat = "latest"
fd = "latest"
neovim = "latest"
eza = "0.18.17"
zellij = "0.40.1"
usage = "latest"
glow = "1.5.0"
go = "1.23.4"
node = "22.9.0"
ruby = "3.3.4"
